<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tex</string>
		<string>lhs</string>
		<string>sty</string>
	</array>
	<key>name</key>
	<string>LaTeX Prime</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>%.*$</string>
			<key>name</key>
			<string>comment.latex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$\$</string>
			<key>end</key>
			<string>\$\$</string>
			<key>name</key>
			<string>markup.other.math.latex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\\\[</string>
			<key>end</key>
			<string>\\\]</string>
			<key>name</key>
			<string>markup.other.math.latex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)\$</string>
			<key>end</key>
			<string>(?&lt;!\\)\$</string>
			<key>name</key>
			<string>markup.other.math.latex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\\\(</string>
			<key>end</key>
			<string>\\\)</string>
			<key>name</key>
			<string>markup.other.math.latex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\emph){</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.italic.latex</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.definition.emphasis.latex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\begin){code}(\s*\n)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.raw.code.latex</string>
			<key>end</key>
			<string>(\\end){code}</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.code.latex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)\|</string>
			<key>end</key>
			<string>\|</string>
			<key>name</key>
			<string>markup.raw.code.latex</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\(sub)*(chapter|section)){(.*)}</string>
			<key>name</key>
			<string>meta.function.section.latex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\[a-zA-Z]+(?:\s|\n?)?</string>
			<key>name</key>
			<string>support.function.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.latex</string>
	<key>uuid</key>
	<string>c89355a8-244a-45c2-9ba7-2e842e87879c</string>
</dict>
</plist>
